<template>
    <div id="tos">
        <h1></h1>
        <p>The following terms and conditions govern all use of the GDPR App, GDPRapp.org website and all content, services and products available at or through the website, including, but not limited to, the GDPRapp.org, (taken together, the Website). The App and Website is offered subject to your acceptance without modification of all of the terms and conditions contained herein and all other operating rules, policies (including, without limitation, <b>GDPR Privacy Policy</b>) and procedures that may be published from time to time on this Site by GDPR (collectively, the “Agreement”).</p>
        <p>Please read this Agreement carefully before accessing or using the GDPR App and Website. By accessing or using any part of the App and Web site, you agree to become bound by the terms and conditions of this agreement. If you do not agree to all the terms and conditions of this agreement, then you may not access the Website or use any services. If these terms and conditions are considered an offer by GDPR, acceptance is expressly limited to these terms. GDPR services are available only to individuals who are at least 16 years old.</p>
        <h2>Your GDPR Account and Site</h2>
        <p>If you create an account on the App or Website, you are responsible for maintaining the security of your account, and you are fully responsible for all activities that occur under the account and any other actions taken in connection with the account. You must immediately notify GDPR of any unauthorized uses of your account or any other breaches of security. GDPR will not be liable for any acts or omissions by You, including any damages of any kind incurred as a result of such acts or omissions.</p>
        <h2>Responsibility of Contributors</h2>
        <p>By submitting Content to GDPR for inclusion on your account, you grant GDPR a world-wide, royalty-free, and non-exclusive license to reproduce, modify, adapt and publish the Content solely for the purpose of displaying, distributing and promoting your account. If you delete Content, GDPR will use reasonable efforts to remove it from the App and Website, but you acknowledge that caching or references to the Content may not be made immediately unavailable.</p>
        <p>Without limiting any of those representations or warranties, GDPR has the right (though not the obligation) to, in GDPR’s sole discretion (i) refuse or remove any content that, in GDPR’s reasonable opinion, violates any GDPR policy or is in any way harmful or objectionable, or (ii) terminate or deny access to and use of the App and Website to any individual or entity for any reason, in GDPR’s sole discretion. GDPR will have no obligation to provide a refund of any amounts previously paid.</p>
        <h2>Restricted Use</h2>
        <p>You may not use the GDPR app or GDPRapp.org to substantially replicate products or services offered by GDPR. If GDPR believes, in its sole discretion, that you have violated or attempted to violate these conditions or the spirit of these terms, your ability to use and access the GDPR App or GDPRapp.org may be temporarily or permanently revoked, with or without notice.</p>
        <p>You are responsible for taking precautions as necessary to protect yourself and your computer systems from viruses, worms, Trojan horses, and other harmful or destructive content. The Website may contain content that is offensive, indecent, or otherwise objectionable, as well as content containing technical inaccuracies, typographical mistakes, and other errors. The Website may also contain material that violates the privacy or publicity rights, or infringes the intellectual property and other proprietary rights, of third parties, or the downloading, copying or use of which is subject to additional terms and conditions, stated or unstated. GDPR disclaims any responsibility for any harm resulting from the use by visitors of the Website, or from any downloading by those visitors of content there posted.</p>
        <h2>Content Posted on Other Websites</h2>
        <p>We have not reviewed, and cannot review, all of the material, including computer software, made available through the websites and webpages to which the GDPR App or GDPRapp.org links, and that link to GDPRapp.org. GDPR does not have any control over those non-GDPR websites and webpages, and is not responsible for their contents or their use. By linking to a non-GDPR website or webpage, GDPR does not represent or imply that it endorses such website or webpage. You are responsible for taking precautions as necessary to protect yourself and your computer systems from viruses, worms, Trojan horses, and other harmful or destructive content. GDPR disclaims any responsibility for any harm resulting from your use of non-GDPR websites and webpages.</p>
        <h2>Intellectual Property</h2>
        <p>This Agreement does not transfer from GDPR to you any GDPR or third party intellectual property, and all right, title and interest in and to such property will remain (as between the parties) solely with GDPR. GDPR, GDPRapp.org, the GDPR logo, and all other trademarks, service marks, graphics and logos used in connection with GDPR, or the Website are trademarks or GDPR’s licensors. Other trademarks, service marks, graphics and logos used in connection with the Website may be the trademarks of other third parties. Your use of the Website grants you no right or license to reproduce or otherwise use any GDPR or third-party trademarks. Advertisements.</p>
        <h2>Changes</h2>
        <p>GDPR reserves the right, at its sole discretion, to modify or replace any part of this Agreement. It is your responsibility to check this Agreement periodically for changes. Your continued use of or access to the Website following the posting of any changes to this Agreement constitutes acceptance of those changes. GDPR may also, in the future, offer new services and/or features through the Website (including, the release of new tools and resources). Such new features and/or services shall be subject to the terms and conditions of this Agreement.</p>
        <h2>Termination</h2>
        <p>GDPR may terminate your access to all or any part of the Website and App at any time, with or without cause, with or without notice, effective immediately. If you wish to terminate this Agreement or your GDPR account (if you have one), you may simply discontinue using the Website or App. You can file a request to delete all stored data about you here. GDPR can terminate access to the App and Website immediately as part of a general shut down of our service. All provisions of this Agreement which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity and limitations of liability.</p>
        <h2>Disclaimer of Warranties</h2>
        <p>The Website is provided “as is”. GDPR and its suppliers and licensors hereby disclaim all warranties of any kind, express or implied, including, without limitation, the warranties of merchantability, fitness for a particular purpose and non-infringement. Neither GDPR nor its suppliers and licensors, makes any warranty that the Website will be error free or that access thereto will be continuous or uninterrupted. If you’re actually reading this, here’s a treat. You understand that you download from, or otherwise obtain content or services through, the Website at your own discretion and risk.</p>
        <h2>Limitation of Liability</h2>
        <p>In no event will Franz, or its suppliers or licensors, be liable with respect to any subject matter of this agreement under any contract, negligence, strict liability or other legal or equitable theory for: (i) any special, incidental or consequential damages; (ii) the cost of procurement for substitute products or services; (iii) for interruption of use or loss or corruption of data; or (iv) for any amounts that exceed the fees paid by you to GDPR under this agreement during the twelve (12) month period prior to the cause of action. GDPR shall have no liability for any failure or delay due to matters beyond their reasonable control. The foregoing shall not apply to the extent prohibited by applicable law.</p>
        <h2>General Representation and Warranty</h2>
        <p>You represent and warrant that (i) your use of the Website will be in strict accordance with the <b>GDPR Privacy Policy</b> with this Agreement and with all applicable laws and regulations (including without limitation any local laws or regulations in your country, state, city, or other governmental area, regarding online conduct and acceptable content, and including all applicable laws regarding the transmission of technical data exported from the United States or the country in which you reside) and (ii) your use of the Website will not infringe or misappropriate the intellectual property rights of any third party.</p>
        <h2>Indemnification</h2>
        <p>You agree to indemnify and hold harmless GDPR, its contractors, and its licensors, and their respective directors, officers, employees and agents from and against any and all claims and expenses, including attorneys’ fees, arising out of your use of the Website or App, including but not limited to your violation of this Agreement.</p>
        <h2>Miscellaneous</h2>
        <p>This Agreement constitutes the entire agreement between GDPR and you concerning the subject matter hereof, and they may only be modified by a written amendment signed by an authorized executive of GDPR, or by the posting by GDPR of a revised version. Except to the extent applicable law, if any, provides otherwise, this Agreement, any access to or use of the GDPR App or Website will be governed by the laws of the United States, excluding its conflict of law provisions, and the proper venue for any disputes arising out of or relating to any of the same will be the state and federal courts located in California, USA. If any part of this Agreement is held invalid or unenforceable, that part will be construed to reflect the parties’ original intent, and the remaining portions will remain in full force and effect. A waiver by either party of any term or condition of this Agreement or any breach thereof, in any one instance, will not waive such term or condition or any subsequent breach thereof. You may assign your rights under this Agreement to any party that consents to, and agrees to be bound by, its terms and conditions; GDPR may assign its rights under this Agreement without condition. This Agreement will be binding upon and will inure to the benefit of the parties, their successors and permitted assigns.</p>
    </div>
</template>
<script>
export default {
    name: 'tos-txt'
}
</script>
